[features]
seeds = false
[programs.localnet]
solana_twitter = "91Akrzp5257wNcvVWkCEikzN5yqEZUAaXtRYaWnukZhe"

[programs.devnet]
solana_twitter = "91Akrzp5257wNcvVWkCEikzN5yqEZUAaXtRYaWnukZhe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/cuongngo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"

[workspace]
types = "app/src/idl"